{
    "name": "GarageDoorControl",
    "version": "1.0.9",
    "icon": "fas fa-warehouse",
    "category": "automation",
    "author": "mjlill",
    "maintainers": [
        "maxbachmann",
        "Psychokiller1888"
    ],
    "desc": "Garage door control",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [],
    "pipRequirements": [
        "RPi.GPIO"
    ],
    "conditions": {
        "lang": [
            "en",
            "de"
        ]
    }
}